name: Publish TypeScript SDK

on:
  push:
    tags:
      - "ts-v*"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: "24"
          package-manager-cache: false
          registry-url: "https://registry.npmjs.org"

      - name: Install
        working-directory: sdk/typescript
        run: npm ci

      - name: Build
        working-directory: sdk/typescript
        run: npm run build

      - name: Publish
        working-directory: sdk/typescript
        run: npm publish
